name: roofs_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - asttokens=2.4.1
  - backcall=0.2.0
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.4
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.8.19
  - python_abi=3.8
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - anyio==4.4.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - attr==0.3.1
      - attrs==23.2.0
      - azure-core==1.30.2
      - azure-storage-blob==12.20.0
      - bleach==5.0.1
      - boto==2.49.0
      - boto3==1.34.124
      - botocore==1.34.124
      - boxing==0.1.4
      - cachetools==5.3.3
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.1.1
      - cryptography==42.0.8
      - cycler==0.12.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - django==3.2.25
      - django-annoying==0.10.6
      - django-cors-headers==3.6.0
      - django-csp==3.7
      - django-debug-toolbar==3.2.1
      - django-environ==0.10.0
      - django-extensions==3.1.0
      - django-filter==2.4.0
      - django-model-utils==4.1.1
      - django-ranged-fileresponse==0.1.2
      - django-rq==2.5.1
      - django-storages==1.12.3
      - django-user-agents==0.4.0
      - djangorestframework==3.13.1
      - drf-dynamic-fields==0.3.0
      - drf-flex-fields==0.9.5
      - drf-generators==0.3.0
      - exceptiongroup==1.2.1
      - expiringdict==1.2.2
      - filelock==3.13.1
      - fonttools==4.53.0
      - fsspec==2024.2.0
      - google-api-core==2.19.0
      - google-auth==2.30.0
      - google-cloud-appengine-logging==1.4.3
      - google-cloud-audit-log==0.2.5
      - google-cloud-core==2.4.1
      - google-cloud-logging==3.10.0
      - google-cloud-storage==2.17.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.1
      - googleapis-common-protos==1.63.1
      - grpc-google-iam-v1==0.13.0
      - grpcio==1.64.1
      - grpcio-status==1.62.2
      - h11==0.14.0
      - htmlmin==0.1.12
      - httpcore==1.0.5
      - httpx==0.27.0
      - humansignal-drf-yasg==1.21.9
      - idna==3.7
      - ijson==3.2.3
      - importlib-resources==6.4.0
      - inflection==0.5.1
      - isodate==0.6.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==3.2.0
      - kiwisolver==1.4.5
      - label-studio==1.12.1
      - label-studio-converter==0.0.58
      - label-studio-tools==0.0.4
      - launchdarkly-server-sdk==8.2.1
      - lockfile==0.12.2
      - lxml==5.2.2
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.0
      - nltk==3.6.7
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - openai==1.33.0
      - opencv-python==4.10.0.82
      - ordered-set==4.0.2
      - pandas==2.0.3
      - pillow==10.3.0
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psycopg2-binary==2.9.9
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==1.10.16
      - pyparsing==3.1.2
      - pyrfc3339==1.1
      - pyrsistent==0.20.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.4
      - pytz==2022.7.1
      - pyyaml==6.0.1
      - redis==3.5.3
      - regex==2024.5.15
      - requests==2.31.0
      - rq==1.10.1
      - rsa==4.9
      - rules==2.2
      - s3transfer==0.10.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semver==3.0.2
      - sentry-sdk==2.5.1
      - sniffio==1.3.1
      - sqlparse==0.5.0
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.3.1+cu118
      - torchaudio==2.3.1+cu118
      - torchvision==0.18.1+cu118
      - tqdm==4.66.4
      - triton==2.3.1
      - tzdata==2024.1
      - ua-parser==0.18.0
      - ujson==5.10.0
      - uritemplate==4.1.1
      - urllib3==1.26.18
      - user-agents==2.2.0
      - webencodings==0.5.1
      - wheel==0.40.0
      - xmljson==0.2.0
